name: Hello World

on:
  pull_request:
    branches:
      - dev

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
        #step1 : Hello World program
      - name: Print Hello World
        run: echo "Hello World"
